services:
    wh.user.notification:
        class: WH\UserBundle\Services\Notification
        arguments: ['@service_container']

    wh.user.password:
        class: WH\UserBundle\Services\Password
        arguments: ['@service_container']

    wh.user.password_resetting:
        class: WH\UserBundle\EventListener\ChangePasswordListener
        arguments: [ @router ]
        tags:
            - { name: kernel.event_subscriber }